### ISSUE TITLE
Missing assembly Microsoft.TeamFoundation.SourceControl.WebApi

### ISSUE THREAD

**Issue by Cheesebaron** [cake-contrib/Cake.Tfs#109]
As I described in: https://github.com/cake-contrib/Cake.Issues.PullRequests.Tfs/issues/111

When running `ReportIssuesToPullRequest` on macOS the assembly `Microsoft.TeamFoundation.SourceControl.WebApi` is missing, getting the error:

```
Error: One or more errors occurred.
	Could not load type of field 'Cake.Tfs.PullRequest.TfsPullRequest:pullRequest' (5) due to: Could not load file or assembly 'Microsoft.TeamFoundation.SourceControl.WebApi, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

I have ensured that I have Cake.Tfs as an Addin:

```
#addin nuget:?package=Cake.Tfs&version=0.3.0
#addin nuget:?package=Cake.Issues&version=0.7.0
#addin nuget:?package=Cake.Issues.MsBuild&version=0.7.0
#addin nuget:?package=Cake.Issues.Reporting&version=0.7.0
#addin nuget:?package=Cake.Issues.Reporting.Generic&version=0.7.1
#addin nuget:?package=Cake.Issues.PullRequests&version=0.7.0
#addin nuget:?package=Cake.Issues.PullRequests.Tfs&version=0.7.1
#tool nuget:?package=MSBuild.Extension.Pack&version=1.9.1
```

I am running mono 5.18.x.

Not sure where this assembly comes from in the first place. But I would assume it is somehow bundled with Visual Studio on Windows. While on macOS it is simply not there.

**Comment by pascalberger** [comment]
The assemblies are bundled as resources through Costura Fody in this release and `Microsoft.TeamFoundation.SourceControl.WebApi` is part of it.

Are you in a position to try to update the `Microsoft.TeamFoundationServer.Client` and `Microsoft.VisualStudio.Services.InteractiveClient` client assemblies to the latest 16.x preview version?

**Comment by Cheesebaron** [comment]
Do you mean updating it in Cake.Tfs, build it and use my own built version of Cake.Tfs to try it?

**Comment by pascalberger** [comment]
Yes, I unfortunately don't have a Mac available at the moment (and haven't got around to create Mac/Linux test pipelines yet)

**Comment by Cheesebaron** [comment]
Will give it a try :) I'll let you know what I find out.

**Comment by pascalberger** [comment]
If it makes it easier for you, you can also try with a simple repro script which just uses Cake.Tfs like in [this](https://cake-contrib.github.io/Cake.Tfs/docs/usage/read-pullrequest) example. If this works I expect that it should also work for Cake.Issues.

**Comment by pascalberger** [comment]
@Cheesebaron There's now a build with latest Azure DevOps assemblies included available on [MyGet](https://myget.org/feed/cake-contrib/package/nuget/Cake.Tfs/0.4.0-unstable0022). Could you give this a try and let me know?

**Comment by pascalberger** [comment]
I created a demo project where I could test it against macOS and Linux and still seems to be an issue with latest CI version. See [here](https://dev.azure.com/pberger/Cake.Tfs-Demo/_build/results?buildId=72&view=logs&jobId=a5e52b91-c83f-5429-4a68-c246fc63a4f7&taskId=00f564b5-c6ae-5329-43c9-96bc79a72ec9&lineStart=348&lineEnd=349&colStart=1&colEnd=1)

**Comment by pascalberger** [comment]
@Cheesebaron I changed to addin to target .NET Standard 2.0 which should fix the issue. Can you give [this CI build](https://myget.org/feed/cake-contrib/package/nuget/Cake.Tfs/0.4.0-unstable0031) a try and confirm that it also solves your issue?

**Comment by Cheesebaron** [comment]
@pascalberger sorry, still on vacation, will try it out when I get back. Will let you know.

**Comment by pascalberger** [comment]
No problem. If you want to test with Cake.Issues there is now [Cake.Issues.PullRequests.Tfs 0.7.2-beta.1](https://www.nuget.org/packages/Cake.Issues.PullRequests.Tfs/0.7.2-beta0001) available which 
targets .NET Standard 2.0 and together with [Cake.Tfs 0.3.1-beta.1](https://www.nuget.org/packages/Cake.Tfs/0.3.1-beta0001) should work fine on macOS or Linux.

Enjoy your vacation 🍹

**Comment by pascalberger** [comment]
@Cheesebaron Cake.Tfs 0.3.1 and Cake.Issues.PullRequests.Tfs 0.7.2 have been released new. Let me know if you still have any issues

**Comment by Cheesebaron** [comment]
@pascalberger finally back from vacation. Will try this again soon. Will let you know if this is still an issue 👍

**Comment by pascalberger** [comment]
@Cheesebaron In the meantime Cake.Tfs 0.3.2 is also available which ships with only the required assemblies, since otherwise there could be conflicts in your build script. Would be nice if you could test Cake.Issues.PullRequests.Tfs 0.7.2 with Cake.Tfs 0.3.2 (and if this doesn't work with Cake.Tfs 0.3.1) and let me know if it also works for your use-case.
