### ISSUE TITLE
Add test cases for TFS calls

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Tfs#14]
We should add test cases for the core functionality of this addin using a mock of `GitHttpClient`

Original issue: https://github.com/cake-contrib/Cake.Issues.PullRequests.Tfs/issues/3

**Comment by yansklyarenko** [comment]
@pascalberger Could you please elaborate on this one? As far as I understand, something like this should be done:
- Create an interface with all the methods we call of `GitHttpClient`
- Implement this interface by wrapping the calls to the real `GitHttpClient`
- Use this new class everywhere `GitHttpClient` is currently used
- Mock that interface in the unit tests and cover all public methods currently not covered with tests: `ctor`, `SetStatus`, `Vote`

I would appreciate if you share a couple of lines of preudo-code in case you mean something else. Thanks!

**Comment by pascalberger** [comment]
As a base principle I would like to keep the TFS assemblies / types internal (to allow e.g. #13). I think another wrapper around `GitHttpClient` adds additional overhead, which I would like to avoid.

How about introducing an internal `IGitClientFactory` and `GitClientFactory`, move the existing `TfsPullRequest.CreateGitClient` implementation to it and pass an instance of it to `TfsPullRequest`. This would allow to have an implemention of `IGitClientFactory` in the test assembly which returns a mock of `GitHttpClient`. Then it should be possible to create tests for the public methods of `TfsPullRequest`, especially the ctor which contains probably the most logic. 

Does this make sense?

**Comment by yansklyarenko** [comment]
Sure, it does! I'll shape it in code and come up with the first draft. We can always adjust from there.
