### ISSUE TITLE
Add TfsPullRequestSettings overload which uses environment variables from Build

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Tfs#29]
Add TfsPullRequestSettings overload which uses available environment variables from TFS / Azure DevOps build (`BUILD_REPOSITORY_URI`, `SYSTEM_PULLREQUEST_PULLREQUESTID`)

**Comment by yansklyarenko** [comment]
Could you please clarify how this new constructor should work?

As far as I understand:

- it should only accept `ITfsCredentials` as a parameter
- it should assert the value of repository Url it gets from the env for `null`
- it should NOT assert either source branch or pull request ID values (as far as I can see, it is handled during the construction of the `TfsPullRequest` object)

Correct?

**Comment by pascalberger** [comment]
There are multiple things which can be done here:

1. Add an Ctor overload `public TfsPullRequestSettings(ITfsCredentials credentials)` which reads `BUILD_REPOSITORY_URI` and `SYSTEM_PULLREQUEST_PULLREQUESTID` environment variable, asserts that they are set and contain a value and the sets `this.RepositoryUrl` and `this.PullRequestId`.
This helps to construct a settings object in a Cake script which is executed in a TFS / Azure DevOps build.
2.  Create a static method `TfsPullRequestSettings.UsingTfsBuildOAuthToken()` which returns an instance using the new ctro from the previous point by passing an instance of `TfsAuthenticationOAuth` to it with the value from the `SYSTEM_ACCESSTOKEN` environment variable.
This helps to construct a settings object in a Cake script which is executed in a TFS / Azure DevOps build which has an OAuth token provided to the build. 
3. Add an alias `TfsPullRequestUsingTfsBuildOAuthToken(this ICakeContext context)` which uses settings created by the static method from the previous point.
This makes it even simpler to get access to the pull request in a TFS / Azure DevOps build which has an OAuth token provided to the build.
